# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 346758e46b8176d3bdf97639bcdfa873266f3f984466ad9258dbf6fe68aa472c280f3d354f3043a2a99fc08717d3ff274dcbbe54c11af160571bdd348ec222aa

test:
  secret_key_base: 542f0ac71a601382289c17b088d1d5b0feec368ffd1461b2b8e50a6ec1597ab9df13fae604d9dc2fd41fec394a5eb15a9cb4856fae380b5c17e1e862cda66053

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
